### PR TITLE
Add Infractions section to master branch

### PR DESCRIPTION
**Pull request by spitalnyd**
The infraction section of the code of conduct is complete, all checks pass in Travis and a green checkmark is present. This pull request would merge the team4-infractions branch into the master branch. Please comment your suggestions or concerns, feedback would be appreciated.

### CODE REVIEW

**Review by gkapfham — CHANGES_REQUESTED** [review]
Hi @spitalnyd! Thanks for submitting this PR, I appreciate your hard work on the project.

After reviewing your content, I can see several ways in which you can improve your writing.

- Instead of using passive voice, like "is reviewed" and "will be recorded" please use active voice and then clearly explain who will take this action.
- How are you handling violation(s) of the Allegheny College Honor Code? Are those separate from the infraction of the course's Code of Conduct or is the Honor Code going to be a part of this code?
- Instead of writing "A class member(s)" it would be more clear to write "Class member(s)" instead.

**Comment by enpuyou** [comment]
@spitalnyd Your commit messages could also be more descriptive and specific for the changes you made in that commit instead of just reusing the same commit message overtime.

**Comment by spitalnyd** [comment]
> @spitalnyd Your commit messages could also be more descriptive and specific for the changes you made in that commit instead of just reusing the same commit message overtime.

**Comment by spitalnyd** [comment]
> @spitalnyd Your commit messages could also be more descriptive and specific for the changes you made in that commit instead of just reusing the same commit message overtime.

@enpuyou   Thank-you for the future I will be more descriptive when it comes to my commit messages so everybody understands all the new changes that happened

**Comment by noorbuchi** [comment]
Hi @enpuyou and @gkapfham , I included some clarifications in my latest commit to address some of the issues you brought up. Please let me know if additional changes are needed. Thanks!

**Comment by spitalnyd** [comment]
@gkapfham Thanks for getting feedback so quick. I wanted to let you know I made some grammatical changes, also changed from passive to active. @noorbuchi cleared up the honor code topic as well. Thanks for your time let me know if you have any other questions or concerns.

**Review by enpuyou — APPROVED** [review]

**Review by corlettim — APPROVED** [review]

**Review by gkapfham — CHANGES_REQUESTED** [review]
@gkapfham Thanks for your feedback!! Just completed the small changes you asked for!!

**Review by ibarrezueta — APPROVED** [review]

**Review by gkapfham — APPROVED** [review]
Hello @spitalnyd, I approve this PR. Thanks for your hard work on this task!

**Pull request merged**
